// Public Behavior service API for routes and cross-domain flows.
// Keep this file explicit: behavior owns user actions, settings, activity facts,
// and behavior-shaped response mappers; store/build internals stay behind this boundary.
export {
  completeTodoAction,
  createFavoriteAction,
  createHistoryAction,
  createNoteAction,
  createTodoAction,
  deleteFavoriteAction,
  deleteNoteAction,
  deleteTodoAction,
  updateNoteAction,
  updateTodoAction,
  updateUserAiProviderSettings,
  updateUserSettings,
} from './actions'
export {
  buildActionsOverview,
  buildGrowthKeywords,
  buildJournalOverview,
  buildPersonaSummary,
  buildRadarMetrics,
  buildRecentHistoryItems,
  buildResolvedUserAiProviderSettings,
  buildResolvedUserSettings,
  buildStatsSummary,
  mapFavoriteResponse,
  mapHistoryResponse,
  mapNoteResponse,
  mapTodoResponse,
  parseContentRef,
  parseFavoriteContentRef,
} from './builder'
export {
  appendHistory,
  ensureUserSettingsRow,
  getActionReminderSettings,
  getActivityStreak,
  getCheckedInToday,
  getFavoriteRowById,
  getLatestBriefing,
  getLatestNote,
  getLatestOpportunityFollow,
  getMorningBriefingScheduleState,
  getNoteRow,
  getNoteRowById,
  getProfileCounts,
  getTodoRow,
  getTodoRowById,
  getUserSettings,
  listActiveBriefingSchedules,
  listFavoriteRows,
  listFollowingItemsForActionOverview,
  listHistoryRows,
  listNoteRows,
  listSavedItemsForActionOverview,
  listTodoRows,
  listTodos,
  upsertMorningSchedule,
} from './store'
export type {
  ActionReminderSettingsRow,
  BriefingScheduleRow,
  BriefingScheduleState,
  FavoriteRow,
  FollowingItemRow,
  HistoryRow,
  LatestBriefingRecord,
  LatestNoteRecord,
  LatestOpportunityFollowRecord,
  NoteRow,
  ProfileCounts,
  ResolvedUserAiProviderSettings,
  ResolvedUserSettings,
  SavedItemRow,
  TodoRow,
  UserSettingRow,
} from './types'
