-- Briefing semantic demo seed for local D1.
-- Purpose: provide a stable Today/Briefing data sample for UX and UI review.
-- Target demo user: id=1, test@example.com.

PRAGMA foreign_keys = ON;

INSERT INTO users (
  id, username, email, hashed_password, nickname, avatar, is_active, is_superuser,
  interests, total_read, total_thoughts, total_completed, streak_days, created_at, updated_at, last_login
) VALUES (
  1,
  'testuser',
  'test@example.com',
  'be6eee6cfe51febf1d7fd6838529b150$a929ac4c0832e6c12641347bd458df1f05aad0ec730468e858166365659fa50d',
  '测试用户',
  NULL,
  1,
  0,
  '["AI应用","远程工作","写作素材","数据自动化"]',
  31,
  9,
  4,
  7,
  '2026-03-15 18:22:26',
  '2026-05-01 08:10:00',
  '2026-05-01 08:10:00'
)
ON CONFLICT(id) DO UPDATE SET
  nickname = excluded.nickname,
  interests = excluded.interests,
  total_read = excluded.total_read,
  total_thoughts = excluded.total_thoughts,
  total_completed = excluded.total_completed,
  streak_days = excluded.streak_days,
  updated_at = excluded.updated_at,
  last_login = excluded.last_login;

DELETE FROM user_interests
WHERE user_id = 1;

INSERT INTO user_interests (user_id, interest_name, status, created_at, updated_at)
VALUES
  (1, 'AI应用', 'active', '2026-05-01 08:10:00', '2026-05-01 08:10:00'),
  (1, '远程工作', 'active', '2026-05-01 08:10:00', '2026-05-01 08:10:00'),
  (1, '写作素材', 'active', '2026-05-01 08:10:00', '2026-05-01 08:10:00'),
  (1, '数据自动化', 'active', '2026-05-01 08:10:00', '2026-05-01 08:10:00')
ON CONFLICT(user_id, interest_name) DO UPDATE SET
  status = excluded.status,
  updated_at = excluded.updated_at;

INSERT OR REPLACE INTO hot_topics (
  id, title, summary, content, source, source_url, author, categories, tags, keywords,
  hot_value, view_count, like_count, comment_count, quality_score, relevance_score,
  published_at, fetched_at, hot_comments, guide_questions, raw_data
) VALUES
  (
    9101,
    'AI 代码助手开始进入团队工作台：从个人提效转向流程接入',
    '多款代码助手把重点从单人补全转向任务分派、代码审查和知识库检索，团队开始关心权限、上下文和交付记录。',
    '这条演示内容用于表示 AI 应用从工具演示进入稳定工作流的趋势。它应进入简报头版，并带出后续的原文阅读和对话追问。',
    '演示源·技术产品周刊',
    'https://example.com/briefing-demo/ai-workbench',
    'Demo Desk',
    '["AI应用","开发工具"]',
    '["AI应用","开发工具","团队协作","工作流"]',
    '["AI代码助手","团队工作台","上下文"]',
    1300,
    12800,
    860,
    94,
    9.4,
    9.1,
    '2026-05-01 07:30:00',
    '2026-05-01 08:00:00',
    '[]',
    '["这类工具对个人开发者和团队协作分别意味着什么？","它会改变现有开发流程的哪个环节？"]',
    '{"demo":true,"semantic_role":"lead_candidate","source_layer":"content_candidate"}'
  ),
  (
    9102,
    '远程团队把异步日报改成项目上下文库',
    '一些远程团队不再要求成员写流水账日报，而是把决策、阻塞和下一步沉淀到共享上下文库，方便跨时区协作。',
    '这条演示内容用于承接远程工作关注项。它应展示为关注领域报道，而不是待办任务。',
    '演示源·远程协作观察',
    'https://example.com/briefing-demo/remote-context-log',
    'Demo Desk',
    '["远程工作","知识管理"]',
    '["远程工作","异步协作","知识管理","团队流程"]',
    '["远程团队","异步日报","上下文库"]',
    1260,
    7600,
    430,
    58,
    8.8,
    8.7,
    '2026-05-01 07:10:00',
    '2026-05-01 08:00:00',
    '[]',
    '["什么信息应该进入上下文库？","普通个人如何借鉴这种记录方式？"]',
    '{"demo":true,"semantic_role":"interest_report","source_layer":"content_candidate"}'
  ),
  (
    9103,
    '创作者把长文草稿拆成资料卡片和观点卡片',
    '内容创作者开始把写作流程拆成来源摘录、事实核对、观点卡片和发布草稿，减少临时拼贴带来的混乱。',
    '这条演示内容用于承接写作素材关注项，指导简报页把内容呈现成可阅读材料，而不是催促用户马上写作。',
    '演示源·写作工作流简讯',
    'https://example.com/briefing-demo/writing-cards',
    'Demo Desk',
    '["写作素材","内容创作"]',
    '["写作素材","内容创作","资料卡片","观点卡片"]',
    '["写作流程","资料卡片","观点整理"]',
    1230,
    6900,
    390,
    41,
    8.6,
    8.3,
    '2026-05-01 06:50:00',
    '2026-05-01 08:00:00',
    '[]',
    '["资料卡片和观点卡片如何区分？","这条内容是否能转成个人写作模板？"]',
    '{"demo":true,"semantic_role":"interest_report","source_layer":"content_candidate"}'
  ),
  (
    9104,
    '开源自动化工具新增浏览器任务编排能力',
    '一个开源自动化项目新增浏览器任务编排示例，重点展示登录后页面检查、数据抽取和结果回写的完整链路。',
    '这条演示内容用于承接数据自动化关注项，并提示后续可进入 Article 阅读详情。',
    '演示源·开源项目追踪',
    'https://example.com/briefing-demo/browser-automation-flow',
    'Demo Desk',
    '["数据自动化","开源项目"]',
    '["数据自动化","开源项目","浏览器自动化","工作流"]',
    '["浏览器任务","自动化","数据抽取"]',
    1200,
    5400,
    260,
    35,
    8.2,
    8.1,
    '2026-05-01 06:30:00',
    '2026-05-01 08:00:00',
    '[]',
    '["这类自动化适合哪些稳定流程？","是否需要把它加入待办进一步研究？"]',
    '{"demo":true,"semantic_role":"interest_report","source_layer":"content_candidate"}'
  ),
  (
    9105,
    '高校写作课开始要求标注 AI 辅助过程',
    '部分课程要求学生说明 AI 辅助了资料检索、结构整理还是文字润色，评价重点转向过程透明和个人判断。',
    '这条演示内容用于公共热点区，和用户关注的 AI 应用、写作素材也有交集。',
    '演示源·教育与技术观察',
    'https://example.com/briefing-demo/ai-writing-disclosure',
    'Demo Desk',
    '["AI应用","写作素材","教育"]',
    '["AI应用","写作素材","教育","过程透明"]',
    '["AI辅助写作","课程规范","过程透明"]',
    1170,
    9300,
    510,
    67,
    8.1,
    7.8,
    '2026-05-01 06:20:00',
    '2026-05-01 08:00:00',
    '[]',
    '["过程透明会怎样影响 AI 写作工具？","个人写作记录是否也需要保留辅助过程？"]',
    '{"demo":true,"semantic_role":"public_hotspot","source_layer":"content_candidate"}'
  ),
  (
    9106,
    '效率工具用户更关注可解释推荐，而不是更多提醒',
    '一组用户反馈显示，提醒数量继续增加并不能提高完成率，用户更想知道系统为什么建议自己先看或先做某件事。',
    '这条演示内容用于解释简报页为什么要显示推荐理由和不确定性，而不是只展示列表。',
    '演示源·产品体验样本',
    'https://example.com/briefing-demo/explainable-recommendation',
    'Demo Desk',
    '["AI应用","知识管理","个人效率"]',
    '["AI应用","推荐理由","个人效率","信息筛选","产品体验"]',
    '["可解释推荐","提醒疲劳","信息筛选"]',
    1140,
    6100,
    300,
    29,
    7.9,
    7.6,
    '2026-05-01 06:00:00',
    '2026-05-01 08:00:00',
    '[]',
    '["简报页需要展示哪些推荐理由？","哪些解释会变成噪音？"]',
    '{"demo":true,"semantic_role":"public_hotspot","source_layer":"content_candidate"}'
  );

INSERT OR REPLACE INTO hot_topic_processing_results (
  source_hot_topic_id, source_content_ref, normalized_title, normalized_summary,
  normalized_category_labels_json, normalized_tags_json, quality_score,
  published_at, processing_version, processed_at, is_stale
) VALUES
  (9101, 'hot_topic:9101', 'AI 代码助手开始进入团队工作台', '代码助手正在从个人提效工具转向团队流程入口，关键变化是权限、上下文和交付记录开始被产品化。', '["AI应用","开发工具"]', '["AI应用","开发工具","团队协作","工作流"]', 9.4, '2026-05-01 07:30:00', 'briefing-semantic-demo-v1', '2026-05-01 08:05:00', 0),
  (9102, 'hot_topic:9102', '远程团队把异步日报改成项目上下文库', '远程团队把流水账式日报转成可复用上下文，重点记录决策、阻塞和下一步。', '["远程工作","知识管理"]', '["远程工作","异步协作","知识管理"]', 8.8, '2026-05-01 07:10:00', 'briefing-semantic-demo-v1', '2026-05-01 08:05:00', 0),
  (9103, 'hot_topic:9103', '长文草稿被拆成资料卡片和观点卡片', '写作流程开始显式区分来源、事实核对、观点和发布草稿，降低临时拼贴带来的混乱。', '["写作素材","内容创作"]', '["写作素材","内容创作","资料卡片"]', 8.6, '2026-05-01 06:50:00', 'briefing-semantic-demo-v1', '2026-05-01 08:05:00', 0),
  (9104, 'hot_topic:9104', '开源自动化工具新增浏览器任务编排能力', '浏览器任务编排示例把页面检查、数据抽取和结果回写串成完整链路。', '["数据自动化","开源项目"]', '["数据自动化","开源项目","浏览器自动化"]', 8.2, '2026-05-01 06:30:00', 'briefing-semantic-demo-v1', '2026-05-01 08:05:00', 0),
  (9105, 'hot_topic:9105', '高校写作课要求标注 AI 辅助过程', '课程评价开始关注 AI 辅助发生在检索、结构还是润色阶段，强调过程透明。', '["AI应用","写作素材","教育"]', '["AI应用","写作素材","教育"]', 8.1, '2026-05-01 06:20:00', 'briefing-semantic-demo-v1', '2026-05-01 08:05:00', 0),
  (9106, 'hot_topic:9106', '效率工具用户更关注可解释推荐', '用户不只是需要更多提醒，也需要知道系统为什么建议自己先看或先做某件事。', '["AI应用","知识管理","个人效率"]', '["AI应用","推荐理由","个人效率","信息筛选"]', 7.9, '2026-05-01 06:00:00', 'briefing-semantic-demo-v1', '2026-05-01 08:05:00', 0);

INSERT OR REPLACE INTO opportunities (
  id, title, type, status, source, source_url, source_id, content, summary, requirements,
  published_at, deadline, start_time, reward, reward_min, reward_max, reward_unit,
  location, is_remote, tags, category, quality_score, reliability_score,
  view_count, favorite_count, fetched_at, updated_at, raw_data
) VALUES
  (
    9201,
    '把 AI 应用工作流拆解写成一篇对外文章',
    'submission',
    'active',
    '演示源·写作机会板',
    'https://example.com/briefing-demo/opportunity-ai-workflow-writing',
    'demo-op-9201',
    '征集真实 AI 应用工作流拆解文章，要求说明问题背景、数据来源、工具链和结果。',
    '适合把今天的 AI 应用头版内容转成写作选题，但应在待办页管理进度。',
    '需要 1200 字以上文章草稿和至少 2 个来源链接。',
    '2026-05-01 07:20:00',
    '2026-05-06',
    NULL,
    '入选后获得专题推荐',
    NULL,
    NULL,
    NULL,
    'remote',
    1,
    '["AI应用","写作素材","内容创作"]',
    'writing',
    8.7,
    8.0,
    3200,
    12,
    '2026-05-01 08:00:00',
    '2026-05-01 08:00:00',
    '{"demo":true,"semantic_role":"todo_candidate"}'
  ),
  (
    9202,
    '远程产品助理：整理用户反馈和知识库',
    'job',
    'active',
    '演示源·远程机会板',
    'https://example.com/briefing-demo/opportunity-remote-product-assistant',
    'demo-op-9202',
    '远程产品团队招募兼职助理，主要整理用户反馈、会议记录和产品知识库。',
    '与远程工作和知识管理方向相关，可作为后续跟进线索。',
    '需要熟悉异步协作、基础文档整理和简单数据表。',
    '2026-05-01 07:00:00',
    '2026-05-10',
    NULL,
    '远程兼职',
    NULL,
    NULL,
    NULL,
    'remote',
    1,
    '["远程工作","知识管理","产品"]',
    'job',
    8.3,
    7.8,
    2800,
    9,
    '2026-05-01 08:00:00',
    '2026-05-01 08:00:00',
    '{"demo":true,"semantic_role":"todo_candidate"}'
  ),
  (
    9203,
    '开源自动化项目征集真实工作流案例',
    'contribution',
    'active',
    '演示源·开源任务栏',
    'https://example.com/briefing-demo/opportunity-automation-case',
    'demo-op-9203',
    '项目维护者征集浏览器自动化、资料归档和数据回写案例，用于完善模板库。',
    '与数据自动化方向相关，但应作为可转待办线索，不抢简报主体。',
    '需要提交流程说明、输入输出样例和失败处理。',
    '2026-05-01 06:45:00',
    '2026-05-12',
    NULL,
    '贡献者署名',
    NULL,
    NULL,
    NULL,
    'remote',
    1,
    '["数据自动化","开源项目","工作流"]',
    'open_source',
    8.1,
    7.6,
    1900,
    5,
    '2026-05-01 08:00:00',
    '2026-05-01 08:00:00',
    '{"demo":true,"semantic_role":"todo_candidate"}'
  );

INSERT INTO briefings (
  user_id, briefing_date, briefing_type, issue_number, title, summary_text, payload,
  status, generated_at, created_at, updated_at
) VALUES (
  1,
  '2026-05-01',
  'morning',
  20260501,
  '今日内容摘要',
  '今天这份简报围绕 AI 应用、远程工作、写作素材和数据自动化展开：AI 代码助手正在从个人提效工具进入团队工作台，远程团队把日报改造成可复用上下文，写作者开始把资料和观点分开管理。你可以先读头版和关注领域报道，再打开原文核对细节。',
  '{"schemaVersion":"today-briefing-demo-v1","semanticFlow":{"userInterests":["AI应用","远程工作","写作素材","数据自动化"],"sourceLayer":"hot_topics/opportunities demo candidates","processingLayer":"hot_topic_processing_results","pageLayer":"TodayPageData"},"dailyAngle":"AI 应用正在从工具演示转向稳定工作流，远程协作和写作沉淀都开始强调可追溯上下文。","aiBriefing":{"version":"today-briefing-demo-v1","provider":"demo-seed","model":"curated-semantic-template","status":"success","leadSummary":"今天的核心变化不是又出现了一个新工具，而是多个方向都在把零散信息变成可复用工作流：AI 代码助手进入团队流程，远程日报变成上下文库，写作素材被拆成资料卡片和观点卡片。","topicClusters":[{"title":"AI 应用进入团队工作流","summary":"AI 代码助手的重点从单人补全转向任务分派、代码审查和知识库检索。对你来说，值得关注的不是单点能力，而是它如何改变团队里的上下文、权限和交付记录。","confidenceNote":"基于演示候选内容和处理结果归并，真实环境应继续核对原文。","recommendationReason":"命中你的关注项 AI应用 和 数据自动化。","sourceRefs":[{"contentRef":"hot_topic:9101","title":"AI 代码助手开始进入团队工作台：从个人提效转向流程接入","sourceLabel":"演示源·技术产品周刊","reason":"头版候选，质量分和关注匹配最高"},{"contentRef":"hot_topic:9104","title":"开源自动化工具新增浏览器任务编排能力","sourceLabel":"演示源·开源项目追踪","reason":"补充数据自动化方向"}]},{"title":"远程协作从日报转向上下文沉淀","summary":"远程团队开始减少流水账日报，把决策、阻塞和下一步写进共享上下文库。这条线索适合你观察远程工作的组织方式，而不是马上变成任务。","confidenceNote":"演示数据只覆盖单一来源，真实环境应补充多来源验证。","recommendationReason":"命中你的关注项 远程工作。","sourceRefs":[{"contentRef":"hot_topic:9102","title":"远程团队把异步日报改成项目上下文库","sourceLabel":"演示源·远程协作观察","reason":"远程工作方向的主要报道"}]},{"title":"写作流程开始显式区分资料和观点","summary":"写作者正在把长文草稿拆成来源摘录、事实核对、观点卡片和发布草稿。它更像一种内容生产结构，而不是催促你今天必须写完文章。","confidenceNote":"演示数据用于确认简报语义，不代表真实趋势结论。","recommendationReason":"命中你的关注项 写作素材。","sourceRefs":[{"contentRef":"hot_topic:9103","title":"创作者把长文草稿拆成资料卡片和观点卡片","sourceLabel":"演示源·写作工作流简讯","reason":"写作素材方向的主要报道"},{"contentRef":"hot_topic:9105","title":"高校写作课开始要求标注 AI 辅助过程","sourceLabel":"演示源·教育与技术观察","reason":"公共热点与写作关注有交集"}]}],"recommendationReasons":["优先保留与你关注项直接命中的内容，而不是只按公共热度排序。","头版选择可解释一个跨领域变化：工具、远程协作和写作都在强调上下文沉淀。","待办候选被放在后段，避免把简报页变成任务页。"],"uncertainties":["演示来源为模板数据，真实环境需要核对来源可信度和发布时间。","当前兼容层仍用 hot_topics 承载关注报道，后续可升级为更明确的内容候选表。"],"generatedAt":"2026-05-01T08:10:00+08:00"},"leadItem":{"contentRef":"hot_topic:9101","itemType":"hot_topic","title":"AI 应用进入团队工作流，不再只是个人提效工具","summary":"今天最值得先看的变化是：AI 代码助手、浏览器自动化和团队知识库正在连成工作流。它说明 AI 应用的价值开始从单点能力转向可追溯的协作过程。","sourceLabel":"今日简报 · 6 个候选来源","relevanceLabel":"命中 AI应用、数据自动化","primaryActionLabel":"查看报道","secondaryActionLabel":"记下判断"},"extensionSlots":[{"slotType":"ask","title":"问这份简报","description":"围绕今天的头版重点继续追问，重点核对它对你的项目和写作有什么影响。","actionLabel":"去对话","deepLink":"/chat","sourceContentRef":"hot_topic:9101"},{"slotType":"save","title":"保存头版线索","description":"把 AI 应用进入团队工作流这条线索保存到收藏，后续写作或复盘时再用。","actionLabel":"保存线索","deepLink":"/collections","sourceContentRef":"hot_topic:9101"},{"slotType":"todo","title":"转成待办候选","description":"如果你决定研究自动化工作流，把它交给待办页管理进度。","actionLabel":"查看待办","deepLink":"/todo","sourceContentRef":"opportunity:9203"}]}',
  'ready',
  '2026-05-01 08:10:00',
  '2026-05-01 08:10:00',
  '2026-05-01 08:10:00'
)
ON CONFLICT(user_id, briefing_date, briefing_type) DO UPDATE SET
  issue_number = excluded.issue_number,
  title = excluded.title,
  summary_text = excluded.summary_text,
  payload = excluded.payload,
  status = excluded.status,
  generated_at = excluded.generated_at,
  updated_at = excluded.updated_at;
